"""Tests for the supported framework surface."""

import tempfile
from pathlib import Path

import pytest

from agentman.agent_builder import AgentBuilder
from agentman.agentfile_parser import AgentfileParser


class TestFrameworkSupport:
    """Validate the remaining fast-agent-only framework surface."""

    def test_framework_parsing_fast_agent_default(self):
        """Fast-agent is the default framework."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
"""
        )
        assert config.framework == "fast-agent"

    def test_framework_parsing_fast_agent_explicit(self):
        """Explicit fast-agent declarations are accepted."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
"""
        )
        assert config.framework == "fast-agent"

    def test_framework_validation_rejects_removed_frameworks(self):
        """Removed framework identifiers must be rejected."""
        with pytest.raises(ValueError, match="Unsupported framework: agno"):
            AgentfileParser().parse_content(
                """
FROM python:3.11-slim
FRAMEWORK agno
AGENT test
INSTRUCTION Test agent
"""
            )

        with pytest.raises(ValueError, match="Unsupported framework: invalid-framework"):
            AgentfileParser().parse_content(
                """
FROM python:3.11-slim
FRAMEWORK invalid-framework
AGENT test
INSTRUCTION Test agent
"""
            )

    def test_fast_agent_code_generation(self):
        """Fast-agent code generation remains functional."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
"""
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            code = AgentBuilder(config, temp_dir).framework.build_agent_content()

        assert "from mcp_agent.core.fastagent import FastAgent" in code
        assert 'FastAgent("Generated by Agentman")' in code
        assert "@fast.agent" in code
        assert "async with fast.run() as agent:" in code

    def test_fast_agent_requirements(self):
        """Requirements generation is deterministic for the supported framework."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
"""
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            requirements = AgentBuilder(config, temp_dir).framework.get_requirements()

        assert requirements == ["fast-agent-mcp==0.2.33", "deprecated==1.2.18"]

    def test_fast_agent_config_generation(self):
        """Fast-agent config files are created and no alternate format is emitted."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
SECRET ANTHROPIC_API_KEY
"""
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            builder = AgentBuilder(config, temp_dir)
            builder.framework.generate_config_files()

            assert (Path(temp_dir) / "fastagent.config.yaml").exists()
            assert (Path(temp_dir) / "fastagent.secrets.yaml").exists()
            assert not (Path(temp_dir) / ".env").exists()

    def test_dockerfile_copies_only_fast_agent_config(self):
        """The Dockerfile must copy only the supported framework config files."""
        config = AgentfileParser().parse_content(
            """
FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-sonnet-20241022
AGENT test
INSTRUCTION Test agent
"""
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            builder = AgentBuilder(config, temp_dir)
            builder._generate_dockerfile()

            dockerfile_content = (Path(temp_dir) / "Dockerfile").read_text(encoding="utf-8")

        assert "COPY fastagent.config.yaml ." in dockerfile_content
        assert "COPY fastagent.secrets.yaml ." in dockerfile_content
        assert "COPY .env ." not in dockerfile_content

    def test_agent_specific_model_instruction(self):
        """Agent-scoped MODEL instructions remain supported."""
        config = AgentfileParser().parse_content(
            """FROM python:3.11-slim
FRAMEWORK fast-agent
MODEL anthropic/claude-3-haiku-20240307

MCP_SERVER web_search
COMMAND uvx
ARGS mcp-server-duckduckgo
TRANSPORT stdio

AGENT research_agent
INSTRUCTION You are a research agent
SERVERS web_search
MODEL anthropic/claude-3-sonnet-20241022
USE_HISTORY true
HUMAN_INPUT false
"""
        )

        agent = config.agents["research_agent"]
        assert config.default_model == "anthropic/claude-3-haiku-20240307"
        assert agent.model == "anthropic/claude-3-sonnet-20241022"
        assert agent.use_history is True
        assert agent.human_input is False
        assert agent.servers == ["web_search"]
